language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://jstoebel.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "YXijbNHOjF/HrYphivMUU5nPXmI35wfAMWUpQuBMC2YXWJnzqkadxxsTar0QlNy635mFZ2M5PZxBuYsh8jTndgyp/OGj2/6VbbPxAjpZlEMTDceewOvWAS6ZLhIXOHf8RX0nNvlzf2hdsKb0OHz0EzQQsrnOkHnR4GMW0Cxo5IEWvc+x0RBtUdyn+eWV4BwwhYSzFkjzC8yF2OmQmQoFtLfDUQEKOfxTeAW5Ei+rKxqZRzPQCeZqBYreqylJCf6CWoH3pSb2/S39oTKL31Hjp4BK+uF1uXb7qvZVrBAa/gPn1p36ZorqXlW6NgSbGkbZFKfaC4ts/IEqe/IxiwhDnTkngUKfwVifpnozWgX1P2R/fvfGeKv63Ty58V5naMWnwcFX8Tgd7AloN+vPwaKoAwJ7clWQKzGRaueKBW8HbowQv9E9RJTlEsJPzT9a7KB3yKwwXc3/le2XtBsbtujhvDkNruGjZ1RLN3PHd05WzCPFQ+qHgOZbo5yWncK4mR4zzz1YnhaacENcks1SnnC2o0M4zaUBZM+8D2NGveZNPlw12HtStKq4RBNrtOL026lynb+Hlnz3BA8GMj8VAWNAQq0WgN0bZ679CjJsuf+BYhUZeLj4cBdEWu6Y1E9xxlILMk+sblHQbR2ErT9dolByTALF3NAhOMDPr3mRV4g3+zI="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
