language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://jstoebel.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "MOvynZHjiHdy8c4aJ4SydZFR13fp4AOUy2TmU7mVLUuTP5hChJzLqq8yEXykZtS4Ck9etDv66wsTHIK1EoHDDHw1g0tdZ6DTyM2uxoNXZnbYwEOZWxU8U1vPKcZea6pJ7+mmZNMHfsv/OBrre4XbPz07bd+5kMj9fZ9Mveck0w4kQ0z3El9CJWNh61tkXMCh1lD7z5CittDlWWK5depdje3lO7e+9Em14MxGkM85MCAdSQXKDUqCUGYcQvQtt+Mxwb354/fbNSTYGJFRDvEUKHB17cvRS3gKV9AHlyKNNlXET5SWAfXbBGix9BRyPdDdwwaXMyiH9T8979tRJHjYWuVRCvjT4fBUlXt1NFIzPvQ6s9yIMyPtqUCQJS1ctEtUN9jWWZS6nWG5L4HCFN1olwbi1BcYdD5IxDHjgYcqXwBIys3YJKSdCJO3i/h3GVHbX07eeWLC8NECoxtUOKe8wYbZ8qYX3zpzbR/AiPHoedoYzZz/ZaalFXfIqN15KBUAyUIecxkoYcBZVzqnVldzu3mTigqVkqBFLiU1OtvHfTvM51dGM9+w6QvNbrBggnRM9bTpfodyA5mgk5F0KuweFbQ3uzENyPOW4sPLZvQte76JIAeRfhuejHsJIZ+WfTBveTD17mCHMKO3P9a5R37AT7DHVwKJRo4QOxC8h459epg="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
